---
title: "Git & RStudio"
output: rmdformats::html_docco
editor_options: 
  chunk_output_type: console
---

# Why Git?

**Bad:**

`script.R`, `script.R`, `script.R`...

...I need to go back to the first version, but I overwrote it.

**Better, but still bad:**

- `script_v1.R`
- `script_v2-fix-bug.R`
- `script_v3-fix-bug-final.R`
- `script_v4-fix-bug-final-final.R`

**Good:**

- `script-2021-04-30a-XY.R` 
- `script-2021-04-30b-LJ.R`
- `script-2021-05-03a-XY.R` 
- `script-2021-05-03a-LJ.R` 
- `script-2021-05-03b-LJ.R` 

... But what changed in which version?

**Best: Git!**


| file       | edit by | change log          |
|------------|---------|---------------------|
| `script.R` | XY      | upload first draft  |
| `script.R` | LJ      | fix bug #1          |
| `script.R` | XY      | include new idea #1 |
| `script.R` | LJ      | rearrange structure |
| `script.R` | LJ      | reverse bug fix #1  |

Git lets you and your collaborators

- keep track of all changes
- revert to previous stages of the project at any time without losing
  intermediate work
- share your projects in a reproducible way

# What's Git?

- Version control system
- Central repository for your project (i.e. advanced Dropbox for (text) files)
- Enables collaborative coding on projects 
- Enables you to keep track of all changes and be able to revert to previous points in time

# Basic Workflow

... when you're working on the project

- Edit your files
- **commit** as soon as you've completed any important step
- **push** the commit(s) to the central repository
  → available to all collaborators

... when someone else has worked on it and you want to continue

- **pull** the cloud repository to your local file path to get the most recent version of the project
- edit files
- **commit** and **push** to the cloud repository

# My approach to Git
## When I use it
- For *all* projects I'm working on alone
- For most projects I'm working on collaboratively

## How I use it
- Within RStudio for R projects via the build-in Git interface (keeping track of `.R`, `.Rmd`, `.csv` files)
- Outside RStudio for all text-based files (i.e. LaTeX projects) via a Git GUI (e.g. GitKraken, Git for Desktop)
- no command line necessary

# What else is possible with Git?

Serving web pages directly from your repository

- really nice with R Markdown-generated HTML websites such as this one
- other examples: [Course website](https://lukas-jue.github.io/intro-tidyverse/), [Course slides](https://lukas-jue.github.io/intro-tidyverse/slides/u2-d07-single-df/u2-d07-single-df.html#1)

# Resources

- Setting up Git in RStudio: [Happy Git with R](https://happygitwithr.com/)
- [GitKraken](https://www.gitkraken.com/) (my favorite Git GUI)